# This file is like the application's central configuration sheet.
# Spring Boot reads it at startup and configures behavior based on keys/values.
spring.application.name=windwalker

# Enables the H2 database web console so you can inspect tables in the browser. 
spring.h2.console.enabled=true

#Denotes the URL path for accessing the H2 Console.
spring.h2.console.path=/h2-console

# Configures the database connection:
# - jdbc:h2:mem:testdb → an in-memory H2 database named "testdb"
#   (in-memory means data is lost when the app stops)
spring.datasource.url=jdbc:h2:mem:testdb

# This tells Spring which driver to use to talk to the database.
# A driver translates between Java (JDBC) and the database’s own protocol.
#Spring Boot talks to the database through JDBC. JDBC is a standard API in Java for database communication, and the JDBC driver (like org.h2.Driver) 
#knows how to speak the H2 database’s protocol. Hibernate (the ORM) uses JDBC under the hood to execute SQL and map results to Java objects.
#JDBC provides the API; the H2 driver implements the API and knows how to communicate with H2.
spring.datasource.driver-class-name=org.h2.Driver

# Credentials for H2. "sa" with empty password is the default for H2.
spring.datasource.username=sa
spring.datasource.password=

#Tells Hibernate, the Java Object Relational Mapping (ORM) library, to auto-generate the database on startup and drop it on shutdown.
#Hibernate uses the JDBC connection to send SQL commands to the DB.
#Hibernate creates tables for the entities (DTOs) denoted. It tracks an object's state, manages connections between the app and the database, and executes queries (Java methods turned into SQL behind the scenes.)
spring.jpa.hibernate.ddl-auto=create

#Allows Spring to log SQL to the console to see what Hibernate is doing.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Set number of flights to generate on startup.
flight.generator.count=50

# Show debug-level logs for Spring Security to help troubleshoot authentication/authorization issues.
logging.level.org.springframework.security=DEBUG
